### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by vincecima** [ivandokov/homebrew-contrib#1]
```shell
❯ which python3
/opt/homebrew/bin/python3

~
❯ which phockup
/opt/homebrew/bin/phockup

~
❯ phockup
Traceback (most recent call last):
  File "/opt/homebrew/bin/phockup", line 11, in <module>
    from src.phockup import Phockup
  File "/opt/homebrew/Cellar/phockup/1.12.0/src/phockup.py", line 11, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

Installed phockup via the Formula and getting this error on every run.

I see that https://github.com/ivandokov/homebrew-contrib/commit/1a704490b495abd8331650750acd79a013e135f8 was intended to fix this issue, so not sure why attempt is still failing.

**Comment by ivandokov** [comment]
Have you updated your `brew` formulas? You need to have the latest version in order to get the fixed installation.
Try running `brew upgrade phockup`

**Comment by vincecima** [comment]
```
❯ brew upgrade phockup
Warning: ivandokov/contrib/phockup 1.12.0 already installed
```

BUT, it's now functioning, I have no idea what changed. Thanks!
